# Interactive HTML BOM
kibot:
  version: 1

outputs:
  - name: ibom
    comment: Interactive HTML BOM
    type: ibom
    dir: fabrication/ibom
    options:
      dark_mode: true
      name_format: "index"
