# JLCPCB Fabrication Files
# Reference: https://jlcpcb.com/help/article/how-to-generate-gerber-and-drill-files-in-kicad-8
# Reference: https://github.com/INTI-CMNB/KiBot/blob/ff2c6ff9bd64d3941268876bdf301001cc8290bd/kibot/resources/config_templates/JLCPCB.kibot.yaml

kibot:
  version: 1

filters:
  - name: only_jlc_parts
    comment: "Only parts with JLC code"
    type: generic
    include_only:
      - column: "LCSC"
        regex: '^C\d+'

outputs:
  - name: jlcpcb_gbr
    comment: Gerbers compatible with JLCPCB
    type: gerber
    dir: fabrication/jlcpcb/gerbers
    options:
      exclude_edge_layer: true
      plot_sheet_reference: false
      plot_footprint_refs: true
      plot_footprint_values: false
      force_plot_invisible_refs_vals: false
      tent_vias: true
      use_protel_extensions: true
      create_gerber_job_file: false
      disable_aperture_macros: true
      gerber_precision: 4.6
      use_gerber_x2_attributes: false
      use_gerber_net_attributes: false
      subtract_mask_from_silk: true # Ensure no silkscreen on pads
    layers:
      - F.Cu
      - B.Cu
      - F.Paste
      - B.Paste
      - F.SilkS
      - B.SilkS
      - F.Mask
      - B.Mask
      - Edge.Cuts

  - name: jlcpcb_drl
    comment: Drill files compatible with JLCPCB
    type: excellon
    dir: fabrication/jlcpcb/gerbers
    options:
      pth_and_npth_single_file: false
      pth_id: "-PTH"
      npth_id: "-NPTH"
      metric_units: true
      route_mode_for_oval_holes: false
      output: "%f%i.%x"

  # This creates a single drill map gerber layer for PTH and NPTH holes instead of two
  - name: jlcpcb_drl_map
    comment: Drill files compatible with JLCPCB
    type: excellon
    dir: fabrication/jlcpcb/gerbers
    options:
      generate_drill_files: false
      pth_and_npth_single_file: true
      map:
        output: '%f-%i%I%v.%x'
        type: gerber
      route_mode_for_oval_holes: false
      output: "%f-%i.%x"

  - name: jlcpcb_zip
    comment: ZIP file for JLCPCB
    type: compress
    dir: fabrication/jlcpcb
    options:
      move_files: true
      output: "%f_gerber_jlcpcb.%x"
      files:
        - from_output: jlcpcb_gbr
          dest: /
        - from_output: jlcpcb_drl
          dest: /
        - from_output: jlcpcb_drl_map
          dest: /

  - name: jlcpcb_cpl
    comment: "Pick and place file, JLCPCB style"
    type: position
    dir: fabrication/jlcpcb
    options:
      pre_transform: _rot_footprint_jlcpcb
      output: "%f_cpl_jlcpcb.%x"
      format: CSV
      units: millimeters
      separate_files_for_front_and_back: false
      only_smd: true
      columns:
        - id: Ref
          name: Designator
        - Val
        - Package
        - id: PosX
          name: "Mid X"
        - id: PosY
          name: "Mid Y"
        - id: Rot
          name: Rotation
        - id: Side
          name: Layer

  - name: jlcpcb_bom
    comment: "BOM for JLCPCB"
    type: bom
    dir: fabrication/jlcpcb
    options:
      output: "%f_%i_jlcpcb.%x"
      exclude_filter: "only_jlc_parts"
      ref_separator: ","
      columns:
        - field: Value
          name: Comment
        - field: References
          name: Designator
        - Footprint Type
        - Footprint
        - LCSC
        - JLC
        - field: "Quantity Per PCB"
          name: QTY
      csv:
        hide_pcb_info: true
        hide_stats_info: true
        quote_all: true
