# Export schematics as PDF
kibot:
  version: 1

outputs:
  - name: "schematics_pdf"
    comment: "Print schematics PDF"
    type: pdf_sch_print
    dir: schematics
    options:
      color_theme: '@SCH_COLOR_THEME@'
      background_color: false

...
definitions:
  SCH_COLOR_THEME: dracula
